[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"
mods = "None"

[font]
size = 12

[font.bold]
family = "CaskaydiaMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaMono Nerd Font"
style = "BoldItalic"

[font.italic]
family = "CaskaydiaMono Nerd Font"
style = "MediumItalic"

[font.normal]
family = "CaskaydiaMono Nerd Font"
style = "Medium"

[colors]
draw_bold_text_with_bright_colors=true

[colors.primary]
background = "0x24283b"
foreground = "0xa9b1d6"

[colors.normal]
black = "0x32344a"
red = "0xf7768e"
green = "0x9ece6a"
yellow = "0xe0af68"
blue = "0x7aa2f7"
magenta = "0xad8ee6"
cyan = "0x449dab"
white = "0x9699a8"

[colors.bright]
black = "0x444b6a"
red = "0xff7a93"
green = "0xb9f27c"
yellow = "0xff9e64"
blue = "0x7da6ff"
magenta = "0xbb9af7"
cyan = "0x0db9d7"
white = "0xacb0d0"

[scrolling]
history = 10000
multiplier = 3

[terminal.shell]
program = "/usr/bin/zsh"

[window]
opacity = 1

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 5
y = 5
