require "ultimate.impatient"
require "ultimate.options"
require "ultimate.keymaps"
require "ultimate.plugins"
require "ultimate.comment"
require "ultimate.nvim-tree"
require "ultimate.bufferline"
require "ultimate.lualine"
require "ultimate.toggleterm"
require "ultimate.project"
require "ultimate.alpha"
require "ultimate.whichkey"
require "ultimate.colorscheme"
-- require "ultimate.indentline"
-- require "ultimate.autopairs"
